version: "3.9"
services:
  db:
    image: postgres:14
    ports: 
    - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
    - type: bind
      source: /tmp/postgres-data
      target: ${PGDATA}
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: ${PGDATA}
    networks:
        test_net:
          ipv4_address: ${DATABASE_IP}
  backend:
    build:
      context: ../App-backend
    image: voliboli-backend:latest
    ports: 
    - ${PORT}:${PORT}
    environment:
      DATABASE_IP: ${DATABASE_IP}
    depends_on:
    - db
    networks:
        test_net:
          ipv4_address: 172.35.1.3

  frontend:
      build:
        context: ../App-frontend
      image: voliboli-frontend:latest
      environment:
        DATABASE_IP: ${DATABASE_IP}
      depends_on:
      - db
      - backend
      networks:
         test_net:
            ipv4_address: 172.35.1.4

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 172.35.0.0/16